CREATE TABLE `user` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(32) NOT NULL DEFAULT '',
  `password` char(64) NOT NULL DEFAULT '',
  `email` varchar(128) NOT NULL DEFAULT '',
  `street` varchar(128) NOT NULL DEFAULT '',
  `city` varchar(128) NOT NULL DEFAULT '',
  `state` varchar(128) NOT NULL DEFAULT '',
  `country` varchar(128) NOT NULL DEFAULT '',
  `postal` varchar(8) NOT NULL DEFAULT '',
  `age` int(3) NOT NULL DEFAULT '0',
  `gender` varchar(8) NOT NULL DEFAULT '',
  `smoker` int(3) NOT NULL DEFAULT '0',
  `housing` varchar(32) NOT NULL DEFAULT '',
  `status` varchar(32) NOT NULL DEFAULT '',
  `employment` varchar(32) NOT NULL DEFAULT '',
  `education` varchar(32) NOT NULL DEFAULT '',
  `description` text NOT NULL,
  `height` varchar(8) NOT NULL,
  `bodytype` varchar(32) NOT NULL,
  `haircolor` varchar(32) NOT NULL,
  `prefgender` varchar(8) NOT NULL,
  `prefagestart` int(11) NOT NULL,
  `prefageend` int(11) NOT NULL,
  `radius` varchar(8) NOT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=latin1 COMMENT='latin1_swedish_ci'
